language: python
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

matrix:
    include:
        - python: 2.7
          env: {TOX_ENV: py27}
        - python: 3.5
          env: {TOX_ENV: py35, COVERAGE: 1}
        - python: 3.5
          env: {TOX_ENV: flake8}

install:
    - pip install tox
    - pip install --requirement requirements.txt

script:
    - tox -e $TOX_ENV

after_success:
    - "[ ! -z $COVERAGE ] && bash <(curl -s https://codecov.io/bash) || true"
